name: Update APT Repository

on:
  push:
    branches:
      - main  # Modify this if your default branch is different

jobs:
  update-apt-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update APT Repository
        run: |
          sudo apt-get update --allow-releaseinfo-change

